#!/usr/bin/env node
/**
 * Quick-check Greenhouse API scanner
 * Fetches all companies with api: fields from portals.yml,
 * applies title/location filters, deduplicates against scan-history.tsv,
 * and outputs new matches as JSON.
 */

import { readFileSync, writeFileSync } from 'fs';

const TODAY = '2026-04-14';
const HISTORY_PATH = 'data/scan-history.tsv';

// --- Filters ---
const TITLE_POS = [
  'Software Engineer', 'Backend Engineer', 'Full Stack Engineer',
  'Engineering Manager', 'Data Engineer', 'Data Architect',
  'Data Platform', 'Data Infrastructure', 'Platform Engineer',
  'Infrastructure Engineer', 'Site Reliability', 'SRE', 'DevOps',
  'ML Engineer', 'Machine Learning Engineer', 'ML Platform', 'MLOps',
  'AI Engineer', 'AI Infrastructure', 'NLP', 'LLM',
  'Manager, Software', 'Manager, Data', 'Manager, Platform',
  'Manager, Infrastructure', 'Manager, Engineering', 'Engineering Lead'
];
const TITLE_NEG = [
  'Junior', 'Intern', '.NET', 'Java ', 'iOS', 'Android', 'PHP', 'Ruby',
  'Embedded', 'Firmware', 'FPGA', 'ASIC', 'Blockchain', 'Web3', 'Crypto',
  'Salesforce Admin', 'SAP ', 'Oracle EBS', 'Mainframe', 'COBOL'
];

// Accept list from portals.yml + strict per scout spec
// US Remote, Denver, SF, Los Gatos, Seattle, Bend = ACCEPT
// NYC/Chicago = remote only. Other relocation = REJECT.
const LOC_ACCEPT_CITIES = [
  'denver', 'san francisco', 'los gatos', 'seattle', 'bend, or', 'bend,',
  'long beach',  // Vast's location per portals.yml
  'san jose', 'sunnyvale', 'mountain view', 'santa cruz', 'pittsburgh'
];
// NYC/Chicago only accept if "remote" is explicitly stated
const LOC_NYC_CHICAGO = ['new york', 'nyc', 'chicago', 'brooklyn'];
// Non-US city/country identifiers — reject even if "remote" precedes them
const NON_US = [
  'argentina', 'buenos aires', 'singapore', 'malaysia', 'india', 'brazil',
  'canada', 'ontario', 'british columbia', 'mexico', 'united kingdom',
  'germany', 'france', 'spain', 'netherlands', 'australia', 'japan', 'korea',
  'ireland', 'poland', 'ukraine', 'israel', 'nigeria', 'kenya', 'colombia',
  'chile', 'switzerland', 'austria', 'sweden', 'norway', 'denmark', 'finland',
  'portugal', 'italy', 'belgium', 'czech', 'romania', 'latvia', 'lithuania',
  'estonia', 'hungary', 'turkey', 'south africa', 'new zealand', 'philippines',
  'indonesia', 'thailand', 'vietnam', 'taiwan', 'hong kong', 'china', 'russia',
  'pakistan', 'bangladesh', 'apj', 'emea', 'latam', 'apac'
];

function titleMatch(title) {
  const t = title.toLowerCase();
  const hasPos = TITLE_POS.some(k => t.includes(k.toLowerCase()));
  const hasNeg = TITLE_NEG.some(k => t.includes(k.toLowerCase()));
  return hasPos && !hasNeg;
}

function locMatch(loc) {
  if (!loc) return true; // no location = assume remote-eligible
  const l = loc.toLowerCase().trim();

  // Hard reject: non-US geography detected anywhere in string
  if (NON_US.some(c => l.includes(c))) return false;

  // NYC/Chicago: only if "remote" is also present
  if (LOC_NYC_CHICAGO.some(k => l.includes(k))) return l.includes('remote');

  // Explicit remote (US-only, since NON_US already rejected foreign remotes)
  if (l === 'remote' || l.includes('us remote') || l.includes('remote - us') ||
      l.includes('united states - remote') || l.includes('remote (united states)') ||
      l.includes('remote, us') || l.includes('remote, united states') ||
      l.includes('nationwide') || l.includes('anywhere')) return true;

  // Accept specific target cities
  if (LOC_ACCEPT_CITIES.some(c => l.includes(c))) return true;

  // "United States" alone (no specific city) = likely remote or nationwide
  if (l === 'united states') return true;

  // Bare "remote" with parenthetical city already handled above via NON_US check
  // Any remaining "remote" without a non-US qualifier = accept
  if (l.startsWith('remote') || l.endsWith('remote')) return true;

  // Default: reject on-site US cities not in accept list
  return false;
}

// Load pre-extracted company list (generated by python3 from portals.yml)
const companies = JSON.parse(readFileSync('/tmp/gh-companies.json', 'utf8'));
console.error(`Found ${companies.length} Greenhouse API companies`);

// Normalize URL for dedup: strip query params so
// "https://boards.greenhouse.io/x/jobs/123?gh_jid=123" == "https://boards.greenhouse.io/x/jobs/123"
function normalizeUrl(url) {
  try { return new URL(url).origin + new URL(url).pathname; } catch { return url; }
}

// Load seen URLs
const seenRaw = readFileSync(HISTORY_PATH, 'utf8');
const seenUrls = new Set(
  seenRaw.split('\n').slice(1).map(l => normalizeUrl(l.split('\t')[0])).filter(Boolean)
);
console.error(`Loaded ${seenUrls.size} seen URLs`);

// Fetch with retries
async function fetchJson(url, retries = 2) {
  for (let i = 0; i <= retries; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i === retries) return null;
      await new Promise(r => setTimeout(r, 1000 * (i + 1)));
    }
  }
}

// Build canonical job URL from Greenhouse job object
function buildUrl(company, job) {
  // The jobs API returns absolute_url or we can build from id
  return job.absolute_url || `https://boards.greenhouse.io/${company.toLowerCase()}/jobs/${job.id}`;
}

const results = { matched: [], skipped_title: [], skipped_loc: [], errors: [] };

// Process companies in parallel batches of 8
const BATCH = 8;
for (let i = 0; i < companies.length; i += BATCH) {
  const batch = companies.slice(i, i + BATCH);
  const fetches = batch.map(async (company) => {
    const data = await fetchJson(company.api);
    if (!data) {
      results.errors.push({ company: company.name, api: company.api });
      return;
    }
    const jobs = data.jobs || [];
    for (const job of jobs) {
      const url = buildUrl(company.name, job);
      if (seenUrls.has(normalizeUrl(url))) continue; // already seen
      const title = job.title || '';
      const location = job.location?.name || '';
      if (!titleMatch(title)) {
        results.skipped_title.push({ company: company.name, title, url });
        continue;
      }
      if (!locMatch(location)) {
        results.skipped_loc.push({ company: company.name, title, location, url });
        continue;
      }
      results.matched.push({
        company: company.name,
        title,
        location,
        url,
        date: TODAY,
        portal: 'greenhouse-api'
      });
    }
  });
  await Promise.all(fetches);
  if (i + BATCH < companies.length) {
    process.stderr.write(`  Processed ${Math.min(i + BATCH, companies.length)}/${companies.length} companies\n`);
  }
}

const outPath = '/home/user/career-ops/qc-results.json';
writeFileSync(outPath, JSON.stringify(results, null, 2));
console.error(`Results written to ${outPath}: ${results.matched.length} new matches`);
