#!/usr/bin/env node
/**
 * Quick-check Greenhouse API scanner
 * Fetches all companies with api: fields from portals.yml,
 * applies title/location filters, deduplicates against scan-history.tsv,
 * and outputs new matches as JSON.
 */

import { readFileSync, writeFileSync } from 'fs';

const TODAY = '2026-04-12';
const HISTORY_PATH = 'data/scan-history.tsv';

// --- Filters ---
const TITLE_POS = [
  'Software Engineer', 'Backend Engineer', 'Full Stack Engineer',
  'Engineering Manager', 'Data Engineer', 'Data Architect',
  'Data Platform', 'Data Infrastructure', 'Platform Engineer',
  'Infrastructure Engineer', 'Site Reliability', 'SRE', 'DevOps',
  'ML Engineer', 'Machine Learning Engineer', 'ML Platform', 'MLOps',
  'AI Engineer', 'AI Infrastructure', 'NLP', 'LLM',
  'Manager, Software', 'Manager, Data', 'Manager, Platform',
  'Manager, Infrastructure', 'Manager, Engineering', 'Engineering Lead'
];
const TITLE_NEG = [
  'Junior', 'Intern', '.NET', 'Java ', 'iOS', 'Android', 'PHP', 'Ruby',
  'Embedded', 'Firmware', 'FPGA', 'ASIC', 'Blockchain', 'Web3', 'Crypto',
  'Salesforce Admin', 'SAP ', 'Oracle EBS', 'Mainframe', 'COBOL'
];

// Acceptable US locations (case-insensitive substring match)
const LOC_ACCEPT = [
  'remote', 'united states', 'us remote', 'denver', 'san francisco',
  'los gatos', 'seattle', 'bend', 'san jose', 'sunnyvale', 'mountain view',
  'santa cruz', 'long beach', 'pittsburgh', 'sf', 'nationwide'
];
// NYC/Chicago: only accept if "remote" is also in the location string
const LOC_REMOTE_ONLY = ['new york', 'nyc', 'chicago'];

function titleMatch(title) {
  const t = title.toLowerCase();
  const hasPos = TITLE_POS.some(k => t.includes(k.toLowerCase()));
  const hasNeg = TITLE_NEG.some(k => t.includes(k.toLowerCase()));
  return hasPos && !hasNeg;
}

function locMatch(loc) {
  if (!loc) return true; // no location = assume remote-eligible
  const l = loc.toLowerCase();
  if (LOC_ACCEPT.some(k => l.includes(k))) return true;
  if (LOC_REMOTE_ONLY.some(k => l.includes(k))) {
    return l.includes('remote');
  }
  return false;
}

// Load pre-extracted company list (generated by python3 from portals.yml)
const companies = JSON.parse(readFileSync('/tmp/gh-companies.json', 'utf8'));
console.error(`Found ${companies.length} Greenhouse API companies`);

// Load seen URLs
const seenRaw = readFileSync(HISTORY_PATH, 'utf8');
const seenUrls = new Set(
  seenRaw.split('\n').slice(1).map(l => l.split('\t')[0]).filter(Boolean)
);
console.error(`Loaded ${seenUrls.size} seen URLs`);

// Fetch with retries
async function fetchJson(url, retries = 2) {
  for (let i = 0; i <= retries; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i === retries) return null;
      await new Promise(r => setTimeout(r, 1000 * (i + 1)));
    }
  }
}

// Build canonical job URL from Greenhouse job object
function buildUrl(company, job) {
  // The jobs API returns absolute_url or we can build from id
  return job.absolute_url || `https://boards.greenhouse.io/${company.toLowerCase()}/jobs/${job.id}`;
}

const results = { matched: [], skipped_title: [], skipped_loc: [], errors: [] };

// Process companies in parallel batches of 8
const BATCH = 8;
for (let i = 0; i < companies.length; i += BATCH) {
  const batch = companies.slice(i, i + BATCH);
  const fetches = batch.map(async (company) => {
    const data = await fetchJson(company.api);
    if (!data) {
      results.errors.push({ company: company.name, api: company.api });
      return;
    }
    const jobs = data.jobs || [];
    for (const job of jobs) {
      const url = buildUrl(company.name, job);
      if (seenUrls.has(url)) continue; // already seen
      const title = job.title || '';
      const location = job.location?.name || '';
      if (!titleMatch(title)) {
        results.skipped_title.push({ company: company.name, title, url });
        continue;
      }
      if (!locMatch(location)) {
        results.skipped_loc.push({ company: company.name, title, location, url });
        continue;
      }
      results.matched.push({
        company: company.name,
        title,
        location,
        url,
        date: TODAY,
        portal: 'greenhouse-api'
      });
    }
  });
  await Promise.all(fetches);
  if (i + BATCH < companies.length) {
    process.stderr.write(`  Processed ${Math.min(i + BATCH, companies.length)}/${companies.length} companies\n`);
  }
}

const outPath = '/home/user/career-ops/qc-results.json';
writeFileSync(outPath, JSON.stringify(results, null, 2));
console.error(`Results written to ${outPath}: ${results.matched.length} new matches`);
